language: node_js
sudo: false
notifications:
  email:
  - ZxBing0066@gmail.com
node_js:
- 6.10.0
script:
- |
  if [ "$TEST_TYPE" = test ]; then
    npm test
  else
    npm run $TEST_TYPE
  fi
env:
  matrix:
  - TEST_TYPE=lint
  - TEST_TYPE=test
  - TEST_TYPE=coverage
deploy:
  - provider: npm
    skip_cleanup: true
    email: ZxBing0066@gmail.com
    api_key:
      secure: CmQPzvSKRb2RhsG3yWLVEdIK0LUhctpLjSacPFZn1L5dvdqYv5VoHI5EKNs1Y+zd3jCaQkpAzADVV2SQqIMaUfnshqo0V8jODVn/1YzPwKg8Ux0x9gp80Di7PjmB8wPqNGRVSWUBB/zll37qWTQFgpizTBBXFjtoZ8MvtwWy62UV/hCyrMt78TwMtSDdoXlXXAG5Ja137MGvDKhKIDYRR07abYAVkCUsy6nHwV2gNA61jXimw/mgeRZ/3KJBhJsQezaevOWa7AqMAQe2bXB2IwPM8l2EBkHc7XCC6VOdgnP/xcF8YqLsb0oGXqoGSBJX95MXisyp5TPAlKT7M3h+MyJm0SFIcF1MHFQhrdNU/KZ5yp7d3seCNuL99PgVh3bDjauL5MAychtTr8Lh9PYa5A7MnnuRd283N/RHeRkPI46inQy30mc4IxN+ctLxPQ+4cSPiGeG/8xuy8z9MIGztqxSKaD+gbgN/nTGESHIMDBA49XY05PZhFbS9PWS5rwtWsWINjYDcdg4Uj5A27n8MfU/MrEMC4RAdDoiQKUbGJofND+JfZuN4iBYZfNUSz8HzFh9bJKQe9nD8r2g6XbXgY+722cDkrjQh83CUZBm7Ne7TxQjkHZ2XV7wzY7OKe5ZGRT29cnn4obzhmsnPW25YLHau1Ns9eqPayUwS2cl3NYE=
    on:
      tags: true
      branch: master
      tag: next
      condition: "$TEST_TYPE = lint"
